Popup
Jeanbulambo/Portfolio-repo pull request #12
Opened 2022-06-23 21:16 UTC by Jeanbulambo

## details popup window
# in this project we implement with Daniel the following items:
- When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
- When the user clicks (or taps) the close (X) button, the popup disappears.
- You should implement popups for both mobile and desktop screen sizes:
- Mobile popup

2022-06-23 22:01 UTC, RolandM99 requested changes
Hi  @Jeanbulambo, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

### To highlight 💯 
- Good commit message ✔️ 
- No Linter errors ✔️ 
- Follow Github flow ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on @Rolandm99 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-23 22:01 UTC, RolandM99 commented on script.js
> +  }
- [ ] Kindly, make sure your close button work as expected. For now, when we click on the close button (X) nothing happens, the popup window doesn't disappear.

2022-06-23 22:01 UTC, RolandM99 commented on style.css
> +    flex-wrap: wrap;
- [ ] As asked on the project requirement, your design should look exactly like the design from Figma. Kindly, make sure that your pop-up card for the mobile version fit the popup designed on the Figma framework. The margin, padding, and width,... should be the same.

|Your Design|Figma Design|
|-------------|---------------|
|![image](https://user-images.githubusercontent.com/71874425/175407706-5918d543-5728-4794-89cb-f42e81a4c4ae.png)|![image](https://user-images.githubusercontent.com/71874425/175407902-c1711291-2102-4ac6-a001-06d951258581.png)|

2022-06-23 22:01 UTC, RolandM99 commented on style.css
> +    align-items: baseline;
- [ ] Make sure the elements underlined here below has the same margin-top as margin-left characteristics like on the Figma design. Kindly, fix this issue:
![image](https://user-images.githubusercontent.com/71874425/175421935-c513c13a-f87c-43b2-aff8-74fc85e1dc97.png)

2022-06-24 08:42 UTC, Kossi-stack requested changes
## Hi @Jeanbulambo,

**Good job so far! 👍🏻**
There are some issues that you still need to work on to go to the next project but you are almost there!💪

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966](https://user-images.githubusercontent.com/81444338/170121142-a9f93bb7-38bb-45cc-8327-aab2501ef90a.gif)

## To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Required Changes ♻️

 _Check the comments under the review for more changes_.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-06-24 08:42 UTC, Kossi-stack commented on style.css
> +.headpop {
- [ ] Kindly fix the popup for the mobile version the (x) button is not working and is not well style.
![Captureusainm](https://user-images.githubusercontent.com/81444338/175497992-bdff702b-6b2a-4212-b828-2a0f1968b5d1.PNG)

2022-06-24 08:42 UTC, Kossi-stack commented on style.css
> +.popupc {
- [ ] Kindly fix the popup for the desktop version is not well style.
![Captureusain](https://user-images.githubusercontent.com/81444338/175498065-b2e2e0db-f879-45af-8607-f55b642e16b6.PNG)

2022-06-24 18:48 UTC, Kandy-Peter requested changes
Hi @Jeanbulambo,

Good job so far! I know you have worked hard on implementing the changes requested by the previous reviewer. However, there is an issue that you still need to work on to go to the next project but you are almost there!

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- You  are following GitHub actions :heavy_check_mark: 
## Required Changes ♻️

- [x] Kindly check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-24 18:48 UTC, Kandy-Peter commented on style.css
> +    margin: 0 145px;
- [ ] You still have the same issues with your `popup` window. I think this is due to the element alignment and elements `position`. Please ensure that your `nav` menu is positioned relative to its parent container i.e if the button has as position `absolute` the parent's container should have `position: relative`.
- [ ] Also, make sure that the design desktop design is similar to the Figma template design.  In your case the alignment is too dissimilar, please take the time to resolve it. I know you can do it so go ahead and have good courage! 😊 

Your design

![image](https://user-images.githubusercontent.com/80612925/175646611-0657feb5-a148-42cb-9700-5d75ac500a5d.png)

The Figma design

![image](https://user-images.githubusercontent.com/80612925/175646718-6f760a12-47e4-4184-b231-a77139f21480.png)

2022-06-25 14:15 UTC, youmari approved these changes
# Project Approved :trophy: :tada: 🟢 

Hi @Jeanbulambo 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linters error.
:heavy_check_mark: Details PR title and description.
:heavy_check_mark: Good commit messages.

Cheers and Happy coding!👏👏👏

- [ ] [optional] the problem that requested you the previous reviewer is still not solved but it's one of the requirements even though you should fix that 
![image](https://user-images.githubusercontent.com/61790587/175777361-d3b3d09b-a9f9-4fa5-84f5-9f5ba3c8e263.png)
- [ ] [optional] please make sure that  the button of the pop-up have the same font and the effect on hover and pressed as the ones in the Figma design 
![image](https://user-images.githubusercontent.com/61790587/175777414-74107131-0c95-42ec-916d-1f8e131e1b53.png)


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U02FTTCCU2V)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-06-25 14:33 UTC, merged